import { expect, test } from "@playwright/test";
import { loadWebviewFixture } from "../helpers/webviewFixture";
import { dispatchWebviewMessage, mountChanges, mountPullRequestPreview, readPostedMessages } from "./webviewHarness";
test("Changes renders production payload without Reviews navigation", async ({ page }) => { const fixture=await loadWebviewFixture("changes.small.en.json"); await page.setViewportSize(fixture.viewport); await mountChanges(page, fixture); await expect(page.getByText("Reviews", { exact: true })).toHaveCount(0); await expect(
  page.locator(
    '.section[data-section="changes"] #changes-group-files-staged ' +
      '.row.file[data-stage="staged"][data-path="src/app.ts"] > .name'
  )
).toBeVisible(); for(const id of ["history","stashes"]){const header=page.locator(`.section[data-section="${id}"] > .section-header`);const body=page.locator(`#section-body-${id}`);await header.focus();await page.keyboard.press("Tab");await expect(body).toBeFocused();await page.keyboard.press("PageDown");await expect.poll(()=>body.evaluate(element=>element.scrollTop)).toBeGreaterThan(0);} });
test("Preview uses production content, state, publish and existing-PR actions", async ({ page }) => { const errors: Error[]=[]; page.on("pageerror",error=>errors.push(error)); const fixture=await loadWebviewFixture("pr-preview.populated.en.json"); await mountPullRequestPreview(page,fixture); await expect(page.getByText("Prepare deterministic Pull Request preview coverage")).toBeVisible(); const create=page.getByRole("button",{name:"Create Pull Request on GitHub"}); await expect(create).toBeVisible(); await expect(create).toBeEnabled(); await page.getByRole("tab",{name:/Changed files/}).click(); await expect(page.getByText("src/previewFixture.ts")).toBeVisible(); expect(await import("./webviewHarness").then(x=>x.readPersistedState(page))).toEqual({activeTab:"files",filesReviewMode:"continuous",diffLayoutMode:"unified",localViewed:[]}); await page.getByRole("tab",{name:"Conversation"}).click(); await create.click(); expect(await readPostedMessages(page)).toContainEqual({type:"publishPullRequest",sourceBranch:fixture.payload.sourceBranch,targetBranch:fixture.payload.targetBranch,title:fixture.payload.title,body:fixture.payload.body}); await expect(page.getByRole("button",{name:"Open pull request on GitHub"})).toHaveCount(0); await dispatchWebviewMessage(page,{type:"preview",preview:{...fixture.payload,existingPr:{number:1,url:"https://example.test/pr/1"}}}); const button=page.getByRole("button",{name:"Open pull request on GitHub"}); await expect(button).toBeVisible(); for(const attribute of ["data-tooltip","aria-label"])await expect(button).toHaveAttribute(attribute,"Open pull request on GitHub"); await button.click(); expect(await readPostedMessages(page)).toContainEqual({type:"openExistingPr"}); expect(errors).toEqual([]); });
